version: "3"
services:
  wordpress:
    image: wordpress:5.2
    volumes:
      - ./wp-content:/var/www/html/wp-content
    container_name: test_wp
    ports:
      - "80:80"
    links:
      - db
    env_file: .env
  db:
    image: mariadb
    volumes:
      - ./db-data:/var/lib/mysql
    container_name: test_db
    env_file: .env
